### ISSUE TITLE
Why cant i stream anything?

### ISSUE THREAD

**Issue by Buddie911** [vendz/Cineapp#1]
I click on an episode and nothing happens, all i get is a blank white page. Can you fix this please?

**Comment by vendz** [comment]
@Buddie911 everything is working fine on my end. Please check that you have a stable internet connection

I am closing this issue but if you are still facing the problem then feel free to reopen this issue

**Comment by Buddie911** [comment]
My connection is stable and now i can stream but i was wondering if maybe you could put different sources and subtitles

**Comment by vendz** [comment]
> My connection is stable and now i can stream but i was wondering if maybe you could put different sources and subtitles

Thank you for the suggestion, I will try and add some sources in future releases
