### ISSUE TITLE
good app

### ISSUE THREAD

**Issue by Narvaezniuyen** [vendz/Cineapp#2]
I liked it but I think it would be better if you added the genres with tmdb

**Comment by vendz** [comment]
Thank you! and I will definitely add your suggestion to my TODO list.

**Comment by yogesh-hacker** [comment]
Hello dear user, I also have an app much like it obviously better than it without ads, https://yogesh-hacker.github.io/yogesh-hacker/App

**Comment by DarkCrypt** [comment]
> Hello dear user, I also have an app much like it obviously better than it without ads, https://yogesh-hacker.github.io/yogesh-hacker/App

See this [comment](https://github.com/vendz/Cineapp/issues/10#issuecomment-1951468947).
