### ISSUE TITLE
Build Errors,please help

### ISSUE THREAD

**Issue by scara78** [vendz/Cineapp#5]
Hi, i have errors on build project:

error: cannot find symbol
            case Constants.ACTION_MOVIES_TYPE:
                          ^
  symbol:   variable ACTION_MOVIES_TYPE
  location: class Constants

error: cannot find symbol
            case Constants.COMEDY_MOVIES_TYPE:
                          ^
  symbol:   variable COMEDY_MOVIES_TYPE
  location: class Constants
![Clipboard01](https://user-images.githubusercontent.com/61316528/198820130-ee5dab8d-e7b0-42f9-8007-6ac2cf702ca2.jpg)

**Comment by vendz** [comment]
i have updated the constants file. it should be now sorted
