### ISSUE TITLE
Versioning issue

### ISSUE THREAD

**Issue by IzzySoft** [vendz/Cineapp#6]
Looks like the APKs at all your releases identify as the same version – including the latest one which, according to its tag, should be version 1.2:

    package: name='cf.vandit.cineapp' versionCode='1' versionName='1.0'

Maybe you can fix that [in your `build.gradle`](https://github.com/vendz/Cineapp/blob/master/app/build.gradle#L12)? `versionCode` must be increased with each release (that's what Android uses internally to tell versions apart), `versionName` is what is shown to the user (and thus should be `1.2` with the latest release).

Thanks in advance!

**Comment by himeshM** [comment]
hello sir where is the backend code

**Comment by yogesh-hacker** [comment]
Hello dear user, I also have an app much like it obviously better than it without ads, https://yogesh-hacker.github.io/yogesh-hacker/App

**Comment by DarkCrypt** [comment]
> Hello dear user, I also have an app much like it obviously better than it without ads, https://yogesh-hacker.github.io/yogesh-hacker/App

See this [comment](https://github.com/vendz/Cineapp/issues/10#issuecomment-1951468947).

**Comment by vendz** [comment]
will make the changes.
thanks for letting me know
