### ISSUE TITLE
Not playing

### ISSUE THREAD

**Issue by InstaTechHD** [vendz/Cineapp#7]
There's a lot of ads on the movies so no matter how much i try to play a movie an ad keeps popping up and TV series don't play, could you add a built in video player? Maybe that would help with the ads

**Comment by vendz** [comment]
I am working on it.
Thanks for the feedback!

**Comment by InstaTechHD** [comment]
You're welcome, thank you 😌

**Comment by yogesh-hacker** [comment]
Hello dear user, I also have an app much like it obviously better than it without ads, https://yogesh-hacker.github.io/yogesh-hacker/App

**Comment by DarkCrypt** [comment]
> Hello dear user, I also have an app much like it obviously better than it without ads, https://yogesh-hacker.github.io/yogesh-hacker/App

See this [comment](https://github.com/vendz/Cineapp/issues/10#issuecomment-1951468947).
