### ISSUE TITLE
Sources 

### ISSUE THREAD

**Issue by InstaTechHD** [vendz/Cineapp#8]
Hi, is there any other source that I could add in the meantime with no ads until you integrate the in app video player?

**Comment by DarkCrypt** [comment]
App is unusable because of persistent loading of ads on every video. Can't even select a different source in player.

**Comment by yogesh-hacker** [comment]
Hello dear user, I also have an app much like it obviously better than it without ads, https://yogesh-hacker.github.io/yogesh-hacker/App

**Comment by DarkCrypt** [comment]
> Hello dear user, I also have an app much like it obviously better than it without ads, https://yogesh-hacker.github.io/yogesh-hacker/App

See this [comment](https://github.com/vendz/Cineapp/issues/10#issuecomment-1951468947).
