### ISSUE TITLE
App Icon Has No Logo

### ISSUE THREAD

**Issue by DarkCrypt** [vendz/Cineapp#9]
The logo in the app icon is the generic Android logo. I suggest creating a logo for your app, it would look much better.

**Comment by yogesh-hacker** [comment]
Hello dear user, I also have an app much like it obviously better than it without ads, https://yogesh-hacker.github.io/yogesh-hacker/App

**Comment by DarkCrypt** [comment]
> Hello dear user, I also have an app much like it obviously better than it without ads, https://yogesh-hacker.github.io/yogesh-hacker/App

See this [comment](https://github.com/vendz/Cineapp/issues/10#issuecomment-1951468947).
